### ISSUE TITLE
Issues with building MPL docs

### ISSUE THREAD

**Issue by mrakitin** [matplotlib/mpl-docker#1]
```python
mpl@e92f6493d4fe:/mpl-build/matplotlib/doc$ make html
Running Sphinx v1.8.5
Adding copy buttons to code blocks...
[autosummary] generating autosummary for: api/_as_gen/matplotlib.animation.AVConvBase.rst, api/_as_gen/matplotlib.animation.AVConvFileWriter.rst, api/_as_gen/matplotlib.animation.AVConvWriter.rst, api/_as_gen/matplotlib.animation.AbstractMovieWriter.rst, api/_as_gen/matplotlib.animation.Animation.rst, api/_as_gen/matplotlib.animation.ArtistAnimation.rst, api/_as_gen/matplotlib.animation.FFMpegBase.rst, api/_as_gen/matplotlib.animation.FFMpegFileWriter.rst, api/_as_gen/matplotlib.animation.FFMpegWriter.rst, api/_as_gen/matplotlib.animation.FileMovieWriter.rst, ..., users/prev_whats_new/whats_new_1.4.rst, users/prev_whats_new/whats_new_1.5.rst, users/prev_whats_new/whats_new_2.0.0.rst, users/prev_whats_new/whats_new_2.1.0.rst, users/prev_whats_new/whats_new_2.2.rst, users/prev_whats_new/whats_new_3.0.rst, users/prev_whats_new/whats_new_3.1.0.rst, users/shell.rst, users/whats_new.rst, users/whats_new_old.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from https://pillow.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://matplotlib.org/cycler/objects.inv...
loading intersphinx inventory from https://dateutil.readthedocs.io/en/stable/objects.inv...
generating gallery...
WARNING: /mpl-build/matplotlib/examples/lines_bars_and_markers/errorbar_subsample.py failed to execute correctly: Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 480, in _memory_usage
    out = func()
  File "/opt/conda/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 465, in __call__
    exec(self.code, self.globals)
  File "/mpl-build/matplotlib/examples/lines_bars_and_markers/errorbar_subsample.py", line 36, in <module>
    ax_r.errorbar(x, y1, yerr=y1err, errorevery=(0, 6))
  File "/opt/conda/lib/python3.7/site-packages/matplotlib/__init__.py", line 1601, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 3214, in errorbar
    if errorevery < 1:
TypeError: '<' not supported between instances of 'tuple' and 'int'

generating gallery for gallery/lines_bars_and_markers... [100%] xcorr_acorr_demo.py
generating gallery for gallery/images_contours_and_fields... [100%] watermark_image.py
generating gallery for gallery/subplots_axes_and_figures... [100%] zoom_inset_axes.py
WARNING: /mpl-build/matplotlib/examples/statistics/violinplot.py failed to execute correctly: Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 480, in _memory_usage
    out = func()
  File "/opt/conda/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 465, in __call__
    exec(self.code, self.globals)
  File "/mpl-build/matplotlib/examples/statistics/violinplot.py", line 48, in <module>
    quantiles=[[0.1], [], [], [0.175, 0.954], [0.75], [0.25]])
  File "/opt/conda/lib/python3.7/site-packages/matplotlib/__init__.py", line 1601, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
TypeError: violinplot() got an unexpected keyword argument 'quantiles'


generating gallery for gallery/pie_and_polar_charts... [100%] polar_scatter.py
generating gallery for gallery/text_labels_and_annotations... [ 45%] font_file.py
Exception occurred:
  File "/opt/conda/lib/python3.7/site-packages/matplotlib/font_manager.py", line 1341, in get_font
    return _get_font(filename, hinting_factor)
TypeError: First argument must be a path or file object reading bytes
The full traceback has been saved in /tmp/sphinx-err-5brr786h.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:30: recipe for target 'html' failed
make: *** [html] Error 2
mpl@e92f6493d4fe:/mpl-build/matplotlib/doc$
```

attn @tacaswell

**Comment by tacaswell** [comment]
The issue is we are trying to build the docs from the master branch against a release version which does not yet have the two features being illustrated here (@mrakitin confirmed in private channels that this is with a mpl 3.1.1 installation).

**Comment by mrakitin** [comment]
The latest version of the image from https://hub.docker.com/r/mrakitin/mpl-docker/tags builds the docs fine.
